#!/usr/bin/env ansible-playbook
---
- name: Synchronization
  hosts: localhost
  become: false
  tags: [sync]
  vars:
    debug: true
  roles:
    - role: sync

- name: Cluster prep
  hosts: k3s_cluster
  gather_facts: true
  become: true
  tags: [prep]
  roles:
    - role: prereq
    - role: airgap
    - role: k3s_custom_registries
      when: registry_host is defined

- name: Setup K3S server
  hosts: server
  become: false
  tags: [server]
  roles:
    - role: k3s_server

- name: Setup K3S agent
  hosts: agent
  become: false
  tags: [agent]
  roles:
    - role: k3s_agent
