---
galaxy_info:
  author: Bas Meijer
  description: Install k3s servers
  namespace: bbaassssiiee
  role_name: k3s_server

  license: Apache
  min_ansible_version: "2.16"

  platforms:
    - name: EL
      versions:
        - "8"
  galaxy_tags:
    - k3s

dependencies: []
...
